# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0002_auto_20161215_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='album_logo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
