# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-15 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0003_item_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_cost',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
